### ISSUE TITLE
SUI is having trouble finding something

### ISSUE THREAD

**Issue by Firebomb67** [lordgreggreg/siu-lgg#3]
It told me it couldn't find some path and gave me this string of code:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, SearchOption searchOption)
   at SkinInstaller.skinInstaller.getLastModDate()
   at SkinInstaller.skinInstaller.CreateAllFileListCS(String base2Dir, String fileName, String gameDirectory)
   at SkinInstaller.skinInstaller.ExtractHeroPak(String gameDirectory)
   at SkinInstaller.skinInstaller.fileListWorker1_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by LGGGreg** [comment]
I think you might need to tell LoL to use the old style launcher.

**Comment by Firebomb67** [comment]
What do you mean by that? I'm confused.

**Comment by LGGGreg** [comment]
Sorry, copying the answer from someone else. "the air client is the legacy
client.  If you're missing the air client files, when you launch the new
client, hit the little 'launch legacy client' button at the bottom"
If that is not applicable, try running as admin.

**Comment by Firebomb67** [comment]
Legacy client is not available anymore( I guess riot got rid of it) and I'm the only user. I don't think I run it as an Admin.

**Comment by ghost** [comment]
I'm not seeing the "launch legacy client" button. I tried running SIU as admin but it didn't work. It's complaining about the missing lol_air_client folder.

**Comment by LGGGreg** [comment]
Sorry for such a long delay.
There is a new version 4.35 which should fix this.
Siu should update on its own, but if it does not, you can download it here.
https://sites.google.com/site/siuupdates/SIU%204.35-Lite.zip?attredirects=0
Skins with AIR parts will not have the air parts working, but the rest
should be okay.
I have not had much time to test, so if you see anything please let me know.
